alias: "Water Plants - NFC tag water-plants for 5 minutes"
description: ""
triggers:
  - trigger: tag
    tag_id: water-plants
conditions: []
actions:
  - type: turn_on
    device_id: <esp_home device id>
    entity_id: <esp_home entity id>
    domain: switch
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: <esp_home device id>
    entity_id: <esp_home entity id>
    domain: switch
mode: single
