esphome:
  name: waterplants
  friendly_name: WaterPlants

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<generated_key>"

ota:
  - platform: esphome
    password: "<password>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Alternative WiFi SSID"
    password: "<alternative_wifi_password>"

# Portal web for diagnostics and control
web_server:
  port: 80

# Relay configuration
switch:
  - platform: gpio
    pin: GPIO5
    name: "Relay 1"
    id: relay_1
    restore_mode: ALWAYS_OFF
    inverted: true # Inverted because the relay is active low

# Status LED (optional)
status_led:
  pin: GPIO2

# Wifi Status Signal Sensor (optional)
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  # Uptime Sensor (optional)
  - platform: uptime
    name: "Uptime"

# Phisical button on ESP32 to toggle the relay
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0 # BOOT button
      mode: INPUT_PULLUP
      inverted: true
    name: "Button"
    on_press:
      - switch.toggle: relay_1
captive_portal:
